version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:80'
    volumes:
      # - .:/app
      - /app/node_modules
      - /app/.next

